### ISSUE TITLE
Failed to apply plugin

### ISSUE THREAD

**Issue by xiptos** [Dictanova/gradle-jcasgen-plugin#2]
Hi!

I just tried the plugin but it failed with:
$ ./gradlew clean --stacktrace

FAILURE: Build failed with an exception.
- Where:
  Build file '/Users/rlopes/Dropbox/dev/pcspace/POSTagger/build.gradle' line: 12
- What went wrong:
  A problem occurred evaluating root project 'POSTagger'.
  
  > Failed to apply plugin [id 'com.dictanova.jcasgen']
  > Could not find matching constructor for: org.gradle.api.internal.file.DefaultSourceDirectorySet(org.codehaus.groovy.runtime.GStringImpl, org.gradle.api.internal.file.BaseDirFileResolver)
- Try:
  Run with --info or --debug option to get more log output.
- Exception is:
  org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'POSTagger'.
  at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
  at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:157)
  at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:72)
  at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:162)
  at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
  at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
  at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
  at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
  at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:529)
  at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:90)
  at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
  at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
  at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:125)
  at org.gradle.internal.Factories$1.create(Factories.java:22)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
  at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122)
  at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
  at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
  at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
  at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
  at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
  at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
  at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
  at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
  at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
  at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
  at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
  at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
  at org.gradle.util.Swapper.swap(Swapper.java:38)
  at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
  at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
  at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
  at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
  at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
  at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
  Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'com.dictanova.jcasgen']
  at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:153)
  at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
  at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113)
  at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
  at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
  at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
  at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
  at org.gradle.api.plugins.PluginAware$apply.call(Unknown Source)
  at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:35)
  at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
  at build_307c0auubdv8sx50kn9jts04e.run(/Users/rlopes/Dropbox/dev/pcspace/POSTagger/build.gradle:12)
  at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
  ... 58 more
  Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.gradle.api.internal.file.DefaultSourceDirectorySet(org.codehaus.groovy.runtime.GStringImpl, org.gradle.api.internal.file.BaseDirFileResolver)
  at com.dictanova.jcasgen.gradle.JCasGenSourceDirectory.<init>(JCasGenSourceDirectory.groovy:37)
  at com.dictanova.jcasgen.gradle.JCasGenPlugin.insertJCasGenSourceDirectorySetInto(JCasGenPlugin.groovy:67)
  at com.dictanova.jcasgen.gradle.JCasGenPlugin.this$2$insertJCasGenSourceDirectorySetInto(JCasGenPlugin.groovy)
  at com.dictanova.jcasgen.gradle.JCasGenPlugin.setupJCasGenFor(JCasGenPlugin.groovy:53)
  at com.dictanova.jcasgen.gradle.JCasGenPlugin.this$2$setupJCasGenFor(JCasGenPlugin.groovy)
  at com.dictanova.jcasgen.gradle.JCasGenPlugin$_apply_closure1.doCall(JCasGenPlugin.groovy:38)
  at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
  at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
  at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:115)
  at org.gradle.api.DomainObjectCollection$all.call(Unknown Source)
  at com.dictanova.jcasgen.gradle.JCasGenPlugin.apply(JCasGenPlugin.groovy:37)
  at com.dictanova.jcasgen.gradle.JCasGenPlugin.apply(JCasGenPlugin.groovy)
  at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
  at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
  at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:137)
  ... 69 more

Could it have something to do with this:
https://discuss.gradle.org/t/com-eriwen-gradle-js-fails-with-gradle-2-12/15183
?

Cheers,

**Comment by spraynasal** [comment]
Hi, what does your build.gradle file look like ?
Try upgrading to version 0.4 : https://plugins.gradle.org/plugin/com.dictanova.jcasgen

**Comment by xiptos** [comment]
That solve it! I was using the 0.2 version, according to the github README. Sorry about that!
Thanks a lot!
